apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "neo4j.fullname" . }}-cleanup-pvcs"
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: "{{ include "neo4j.fullname" . }}-cleanup"
      containers:
        - name: kubectl
          image: "{{ include "cleanup.image" . }}"
          imagePullPolicy: {{ .Values.services.neo4j.cleanup.image.imagePullPolicy }}
          command: [ "/bin/sh" ]
          args: 
            - "-c"
            - "kubectl delete pvc -l helm.neo4j.com/instance={{ .Release.Name }} -n {{ .Release.Namespace }} --ignore-not-found"
      restartPolicy: Never
  backoffLimit: 1